#!/usr/bin/env python3
"""Generate and freeze stems for ICON-Primitive experiments.

This script creates the frozen stems used in experiments:
- E0: Vector stem for 1A/1C/1D/1E/1F/1G
- S0: Spatial stem for 1B (LinearType)

Usage:
    python scripts/generate_stems.py --output assets/frozen_stems --seed 123

The generated stems are saved as .pt files and should be committed to the repo
to ensure perfect reproducibility across machines.
"""

from __future__ import annotations

# Allow `python scripts/...py` without requiring `pip install -e .`.
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import argparse
from pathlib import Path

import torch

from icon_primitive.models.stems import create_vector_stem, create_spatial_stem


def generate_vector_stems(output_dir: Path, seed: int = 123) -> dict:
    """Generate vector stems for all supported datasets."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    datasets_config = {
        "mnist": {"input_dim": 784, "output_dim": 256},
        "cifar10": {"input_dim": 3072, "output_dim": 256},
        "imagenet_subset": {"input_dim": 12288, "output_dim": 256},  # 64x64x3
    }
    
    stems = {}
    for dataset, cfg in datasets_config.items():
        stem = create_vector_stem(dataset, output_dim=cfg["output_dim"], seed=seed)
        stem_id = f"E0_vector_{cfg['output_dim']}d_seed{seed}"
        
        # Save
        save_path = output_dir / f"vector_stem_{dataset}_seed{seed}.pt"
        torch.save({
            "stem_id": stem_id,
            "dataset": dataset,
            "input_dim": cfg["input_dim"],
            "output_dim": cfg["output_dim"],
            "seed": seed,
            "state_dict": stem.state_dict(),
        }, save_path)
        
        stems[dataset] = {
            "path": str(save_path),
            "stem_id": stem_id,
        }
        print(f"Saved vector stem for {dataset}: {save_path}")
    
    return stems


def generate_spatial_stems(output_dir: Path, seed: int = 123) -> dict:
    """Generate spatial stems for CIFAR-10."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Spatial stem outputs 16 channels at 8x8 spatial resolution
    out_channels = 16
    stem = create_spatial_stem("cifar10", seed=seed, out_channels=out_channels)
    stem_id = f"S0_spatial_{out_channels}x8x8_seed{seed}"
    
    save_path = output_dir / f"spatial_stem_cifar10_seed{seed}.pt"
    torch.save({
        "stem_id": stem_id,
        "dataset": "cifar10",
        "input_shape": [3, 32, 32],
        "output_shape": [out_channels, 8, 8],
        "seed": seed,
        "state_dict": stem.state_dict(),
    }, save_path)
    
    print(f"Saved spatial stem for cifar10: {save_path}")
    
    return {"cifar10": {"path": str(save_path), "stem_id": stem_id}}


def generate_manifest(output_dir: Path, vector_stems: dict, spatial_stems: dict) -> None:
    """Generate a manifest YAML listing all stems."""
    manifest_path = output_dir / "stems_manifest.yaml"
    
    content = f"""# ICON-Primitive Frozen Stems Manifest
# Generated by scripts/generate_stems.py
# DO NOT MODIFY - these stems must remain fixed for reproducibility

vector_stems:
"""
    for dataset, info in vector_stems.items():
        content += f"""  {dataset}:
    stem_id: "{info['stem_id']}"
    path: "{info['path']}"
"""
    
    content += """
spatial_stems:
"""
    for dataset, info in spatial_stems.items():
        content += f"""  {dataset}:
    stem_id: "{info['stem_id']}"
    path: "{info['path']}"
"""
    
    with open(manifest_path, "w") as f:
        f.write(content)
    
    print(f"Saved stems manifest: {manifest_path}")


def verify_stems(output_dir: Path, seed: int = 123) -> bool:
    """Verify that saved stems match freshly generated ones."""
    print("\nVerifying stem reproducibility...")
    
    # Check vector stem for CIFAR-10
    saved_path = output_dir / f"vector_stem_cifar10_seed{seed}.pt"
    if not saved_path.exists():
        print(f"  ❌ Missing: {saved_path}")
        return False
    
    saved_data = torch.load(saved_path, weights_only=False)
    fresh_stem = create_vector_stem("cifar10", output_dim=256, seed=seed)
    
    for key in fresh_stem.state_dict():
        if not torch.allclose(saved_data["state_dict"][key], fresh_stem.state_dict()[key]):
            print(f"  ❌ Mismatch in {key}")
            return False
    
    print("  ✅ Vector stems verified")
    
    # Check spatial stem
    saved_path = output_dir / f"spatial_stem_cifar10_seed{seed}.pt"
    if not saved_path.exists():
        print(f"  ❌ Missing: {saved_path}")
        return False
    
    saved_data = torch.load(saved_path, weights_only=False)
    fresh_stem = create_spatial_stem("cifar10", seed=seed, out_channels=16)
    
    for key in fresh_stem.state_dict():
        if not torch.allclose(saved_data["state_dict"][key], fresh_stem.state_dict()[key]):
            print(f"  ❌ Mismatch in {key}")
            return False
    
    print("  ✅ Spatial stems verified")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate frozen stems for ICON-Primitive")
    parser.add_argument("--output", type=str, default="assets/frozen_stems",
                        help="Output directory for stems")
    parser.add_argument("--seed", type=int, default=123,
                        help="Random seed for stem generation")
    parser.add_argument("--verify-only", action="store_true",
                        help="Only verify existing stems, don't generate")
    args = parser.parse_args()
    
    output_dir = Path(args.output)
    
    if args.verify_only:
        success = verify_stems(output_dir, args.seed)
        exit(0 if success else 1)
    
    print(f"Generating stems with seed={args.seed}...")
    print(f"Output directory: {output_dir}")
    print()
    
    vector_stems = generate_vector_stems(output_dir, args.seed)
    spatial_stems = generate_spatial_stems(output_dir, args.seed)
    generate_manifest(output_dir, vector_stems, spatial_stems)
    
    print()
    verify_stems(output_dir, args.seed)
    
    print("\n✅ Stem generation complete!")
    print("Remember to commit these files to ensure reproducibility.")


if __name__ == "__main__":
    main()
